# This is a basic workflow to help you get started with Actions

name: hexo_deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: use Node 18
        uses: actions/setup-node@v1
        with: 
          node-version: 18
      - name: npm install
        run: |
          npm install -g hexo-cli
          npm install
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 47.108.154.178 >> ~/.ssh/known_hosts
        env:
         CI: true
         ACTION_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
      - name: hexo build
        run: |
          hexo clean
          hexo generate
        env:
          CI: true
      - name: Deploy
        run: |
          hexo deploy
        #   git config --global user.email "2907476785@qq.com"
        #   git config --global user.name "zhang-shen-wei" 
        
        # uses: easingthemes/ssh-deploy@v2.0.7
        # env:
          # SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          # ARGS: "-avz --delete"
          # SOURCE: "public/"
          # REMOTE_HOST: "47.108.154.178"
          # REMOTE_USER: "root"
          # TARGET: "/home/admin/blog.git"
